---
title: "Introduction"
editor: visual
---

Hello, My name is **Neha Rao**, currently pursuing a Master's degree in **Data Analytics Engineering**. I have 2.5 years of work experience at **Capgemini**, India. I hold a Bachelor's degree in Information Science and Engineering from Mangalore, Karnataka, India which I completed in 2021. My primary education goal for this course is to deepen my understanding of data analytics and its applications in real-time scenarios, particularly within the context of financial sector. I have experience working in various computing environments, including **Python, web development, SQL/DB2, R programming** and **C#**. I am also familiar with **COBOL,CICS and JCL** for mainframe applications. Additionally, I have utilized python-based libraries and tools for statistical computing and data visualization.

Apart from my education, I find happiness in music, playing the guitar, dancing, creating mandala art, and spending time on platforms like Pinterest, Instagram, and LinkedIn. I love to learn and explore new things in my life, so I always say, Learning is a continuous processs, and I strive to maintain a balance between my personal and professional life.
